GoodFriends_ProjectB_RazorPages/Pages/Error.cshtml.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace GoodFriends_ProjectB_RazorPages.Pages;

[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
[IgnoreAntiforgeryToken]
public class ErrorModel : PageModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

    private readonly ILogger<ErrorModel> _logger;

    public ErrorModel(ILogger<ErrorModel> logger)
    {
        _logger = logger;
    }

    public void OnGet()
    {
        RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
    }
}

GoodFriends_ProjectB_RazorPages/Pages/FriendCountryList.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

using Models;
using Microsoft.EntityFrameworkCore;
using Services;
using GoodFriends_ProjectB_RazorPages.Pages;
using Azure.Core;

namespace GoodFriends_ProjectB_RazorPages.Pages
{
    //Demonstrate how to use the model to present a list of objects
    public class FriendCountryList : PageModel
    {
        //Just like for WebApi
        readonly IFriendsService _service = null;
        readonly ILogger<FriendList> _logger = null;

        //public member becomes part of the Model in the Razor page


        [BindProperty]
        public bool UseSeeds { get; set; } = true;
        
     public List<IFriend> Friends { get; set; } = new List<IFriend>();

        public int NrOfFriends { get; set; }

        //Pagination
        public int NrOfPages { get; set; }
        public int PageSize { get; } = 10;

        public int ThisPageNr { get; set; } = 0;
        public int PrevPageNr { get; set; } = 0;
        public int NextPageNr { get; set; } = 0;
        public int NrVisiblePages { get; set; } = 0;

        //ModelBinding for the form
        [BindProperty]
        public string SearchFilter { get; set; } = null;

        //will execute on a Get request
        public async Task<IActionResult> OnGet()
        {   
            //Read a QueryParameters
            if (int.TryParse(Request.Query["pagenr"], out int pagenr))
            {
                ThisPageNr = pagenr;
            }

            SearchFilter = Request.Query["search"];

            //Use the Service
            var resp = await _service.ReadFriendsAsync(UseSeeds, false, SearchFilter, ThisPageNr, PageSize);
           Friends = resp.PageItems;
            NrOfFriends = resp.DbItemsCount;

            //Pagination
            UpdatePagination(resp.DbItemsCount);

            return Page();
        }

        private void UpdatePagination(int nrOfItems)
        {
            //Pagination
            NrOfPages = (int)Math.Ceiling((double)nrOfItems / PageSize);
            PrevPageNr = Math.Max(0, ThisPageNr - 1);
            NextPageNr = Math.Min(NrOfPages - 1, ThisPageNr + 1);
            NrVisiblePages = Math.Min(10, NrOfPages);
        }

        public async Task<IActionResult> OnPostSearch()
        {
            //Use the Service
            var resp = await _service.ReadFriendsAsync(UseSeeds, false, SearchFilter, ThisPageNr, PageSize);
            Friends = resp.PageItems;
            NrOfFriends = resp.DbItemsCount;

            //Pagination
            UpdatePagination(resp.DbItemsCount);

            //Page is rendered as the postback is part of the form tag
            return Page();
        }

        public async Task<IActionResult> OnPostDeleteGroup(Guid groupId)
        {
            await _service.DeleteFriendAsync(groupId);

            //Use the Service
            var resp = await _service.ReadFriendsAsync(UseSeeds, false, SearchFilter, ThisPageNr, PageSize);
            Friends = resp.PageItems;
            NrOfFriends= resp.DbItemsCount;

            //Pagination
            UpdatePagination(resp.DbItemsCount);

            return Page();
        }

        //Inject services just like in WebApi
        public FriendCountryList(IFriendsService service, ILogger<FriendList> logger)
        {
            _logger = logger;
            _service = service;
        }
    }
}

GoodFriends_ProjectB_RazorPages/Pages/FriendINCity.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

using Models;
using Microsoft.EntityFrameworkCore;
using Services;
using GoodFriends_ProjectB_RazorPages.Pages;
using Azure.Core;
using Seido.Utilities.SeedGenerator;
using Models.DTO;

namespace GoodFriends_ProjectB_RazorPages.Pages
{
    //Demonstrate how to use the model to present a list of objects
    public class FriendINCity : PageModel
    {
        //Just like for WebApi
        readonly IFriendsService _service = null;
        readonly ILogger<FriendINCity> _logger = null;
        private readonly SeedGenerator _seedGenerator;


        //public member becomes part of the Model in the Razor page


        [BindProperty]
        public bool UseSeeds { get; set; } = true;
        
        public List<IFriend> Friends { get; set; } = new List<IFriend>();

        public List<IAddress> City { get; set; } = new List<IAddress>();


       // public string City {get; set;}
        




        public int NrOfFriends { get; set; }

        //Pagination
        public int NrOfPages { get; set; }
        public int PageSize { get; } = 5;
 
        [BindProperty]
        public int ThisPageNr { get; set; } = 0;
        public int PrevPageNr { get; set; } = 0;
        public int NextPageNr { get; set; } = 0;
        public int NrVisiblePages { get; set; } = 0;
        public int PresentPages { get; set; } = 0;

        //ModelBinding for the form
        [BindProperty]
        public string SearchFilter { get; set; } = null;

        //will execute on a Get request
        public async Task<IActionResult> OnGet()
        {
            
            
            var city = await _service.ReadAddressesAsync(UseSeeds, false, "Sweden", ThisPageNr, PageSize);
            
            Friends = city.PageItems.SelectMany(f => f.Friends).ToList<IFriend>();

          //  City = friends;
          // Friends = city.PageItems;

    

      

            return Page();
        }

    /*     private void UpdatePagination(int nrOfItems)
        {
            //Pagination
            NrOfPages = (int)Math.Ceiling((double)nrOfItems / PageSize);
            PrevPageNr = Math.Max(0, ThisPageNr - 1);
            NextPageNr = Math.Min(NrOfPages - 1, ThisPageNr + 1);
            NrVisiblePages = Math.Min(10, NrOfPages);
        }

        public async Task<IActionResult> OnPostSearch()
        {
            //Use the Service
            var resp = await _service.ReadFriendsAsync(UseSeeds, false, SearchFilter, ThisPageNr, PageSize);
            Friends = resp.PageItems;
            NrOfFriends = resp.DbItemsCount;

            //Pagination
            UpdatePagination(resp.DbItemsCount);

            //Page is rendered as the postback is part of the form tag
            return Page();
        }

        public async Task<IActionResult> OnPostDeleteGroup(Guid groupId)
        {
            await _service.DeleteFriendAsync(groupId);

            //Use the Service
            var resp = await _service.ReadFriendsAsync(UseSeeds, false, SearchFilter, ThisPageNr, PageSize);
            Friends = resp.PageItems;
            NrOfFriends= resp.DbItemsCount;

            //Pagination
            UpdatePagination(resp.DbItemsCount);

            return Page();
        }

          public async Task<IActionResult> OnPostDelete(Guid id)
        {
          await  _service.DeleteQuoteAsync(id);        
          
            //Pagination
            //UpdatePagination();

            //Use the Service
            var resp = await _service.ReadQuotesAsync(UseSeeds, false, SearchFilter, ThisPageNr, PageSize);
            Quotes = resp.PageItems;

            //Quotes =  await _service.ReadQuoteAsync(id, false);
           // SelectedQuote = _service.ReadQuote(id);

            //Page is rendered as the postback is part of the form tag
            return Page();
        }            

        public async Task<IActionResult> OnPostDeletePet(Guid id)
        {
          await _service.DeletePetAsync(id);        
          
            //Pagination
            //UpdatePagination();

            var resp2 = await _service.ReadPetsAsync(UseSeeds, false, SearchFilter, ThisPageNr, PageSize);
            Pets = resp2.PageItems;
            //Quotes =  await _service.ReadQuoteAsync(id, false);
           // SelectedQuote = _service.ReadQuote(id);

            //Page is rendered as the postback is part of the form tag
            return Page();
        } */
        //Inject services just like in WebApi
        public FriendINCity(IFriendsService service, ILogger<FriendINCity> logger)
        {
            _logger = logger;
            _service = service;
            _seedGenerator = new SeedGenerator();
        }
    }
}

GoodFriends_ProjectB_RazorPages/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace GoodFriends_ProjectB_RazorPages.Pages;

public class IndexModel : PageModel
{
    private readonly ILogger<IndexModel> _logger;

    public IndexModel(ILogger<IndexModel> logger)
    {
        _logger = logger;
    }

    public void OnGet()
    {

    }
}

GoodFriends_ProjectB_RazorPages/Pages/InputModelAddress.cshtml.cs
using System;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using AppStudies.SeidoHelpers;
using Models;
using Microsoft.EntityFrameworkCore;
using Services;
using GoodFriends_ProjectB_RazorPages.Pages.Pages;
using System.Security.Cryptography;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Models.DTO;


namespace GoodFriends_ProjectB_RazorPages.Pages.Pages
{
    //Demonstrate how to read Query parameters
    public class InputModelAddress : PageModel
    {
        //Just like for WebApi
        readonly IFriendsService _service = null;
        readonly ILogger<InputModelAddress>? _logger = null;

        [BindProperty]
        public FamousAddressIM AddressIM { get; set; }

        public string PageHeader { get; set; }

        //public member becomes part of the Model in the Razor page
        public string? ErrorMessage { get; set; } = null;

        public ModelValidationResult ValidationResult { get; set; } = new ModelValidationResult(false, null, null);

        //For Server Side Validation set by IsValid()
        public bool HasValidationErrors { get; set; }
        public IEnumerable<string> ValidationErrorMsgs { get; set; }
        public IEnumerable<KeyValuePair<string, ModelStateEntry>> InvalidKeys { get; set; }


        //Will execute on a Get request
        public async Task<IActionResult> OnGet()
        {
            try
            {
                if (Guid.TryParse(Request.Query["id"], out Guid _id))
                {
                    //Use the Service and populate the InputModel
                    AddressIM =  new FamousAddressIM(await _service.ReadAddressAsync(_id, false));
                    PageHeader = "Edit details of an Address";
                }
                else
                {
                    //Create an empty InputModel
                    AddressIM = new FamousAddressIM();
                    AddressIM.StatusIM = StatusIM.Inserted;
                    PageHeader = "Create a new Adress";
                }
            }
            catch (Exception e)
            {
                ErrorMessage = e.Message;
            }
            return Page();
        }

        public async Task<IActionResult> OnPostUndo()
        {
            //Use the Service and populate the InputModel
            AddressIM = new FamousAddressIM(await _service.ReadAddressAsync(AddressIM.AddressId, false));          
            PageHeader = "Edit details of an Address";
            return Page();
        }

        public async Task<IActionResult> OnPostSave()
        { 
            if (AddressIM.StatusIM == StatusIM.Inserted)
            {
                //It is an create
                var model = AddressIM.UpdateModel(new Address());
                model = await _service.CreateAddressAsync(new AddressCUdto(model));

                AddressIM = new FamousAddressIM(model);
            }
            else
            {
                //It is an update
                //Get orginal
                var model = await _service.ReadAddressAsync(AddressIM.AddressId, true);

                //update the changes and save
                model = AddressIM.UpdateModel(model);
                model = await  _service.UpdateAddressAsync(new AddressCUdto(model));
                
                AddressIM = new FamousAddressIM(model);
            } 
 
            //CHANGE THIS PATHWAY!

            //return Redirect($"~/Studies/Model/Search?search={FriendIM.FriendId}");


            PageHeader = "Edit details of an Address";
            return Page();
        }



        //Inject services just like in WebApi
        public InputModelAddress(IFriendsService service, ILogger<InputModelAddress> logger)
        {
            _logger = logger;
            _service = service;
        }

        #region Input Model
        //InputModel (IM) is locally declared classes that contains ONLY the properties of the Model
        //that are bound to the <form> tag
        //EVERY property must be bound to an <input> tag in the <form>
        //These classes are in center of ModelBinding and Validation
        public enum StatusIM { Unknown, Unchanged, Inserted, Modified, Deleted }

        public class FamousAddressIM
        {
            //Status of InputModel
            public StatusIM StatusIM { get; set; }

            //Properties from Model which is to be edited in the <form>
            public Guid AddressId { get; init; } = Guid.NewGuid();
        

        
            
             [BindProperty]
            [Required(ErrorMessage = "You must provide an StreetAddress")]
               public string StreetAddress { get; set; }

             [BindProperty]
            [Required(ErrorMessage = "You must provide an ZipCode")]
            public int ZipCode { get; set; }

             [BindProperty]
            [Required(ErrorMessage = "You must provide an City")]
             public string City { get; set; }
             [BindProperty]
            [Required(ErrorMessage = "You must provide an Country")]
            public string Country { get; set; }
           



            #region constructors and model update
            public FamousAddressIM(Task<IAddress> task) { StatusIM = StatusIM.Unchanged; }

            //Copy constructor
            public FamousAddressIM(FamousAddressIM original)
            {
                StatusIM = original.StatusIM;

                AddressId = original.AddressId;
                StreetAddress = original.StreetAddress;
                ZipCode = original.ZipCode;
                City = original.City;
                Country = original.Country;
      
                //EditPets = original.EditPets;
            }

            //Model => InputModel constructor
            public FamousAddressIM(IAddress original)
            {
                StatusIM = StatusIM.Unchanged;
                
                AddressId = original.AddressId;
                StreetAddress = original.StreetAddress;
                ZipCode = original.ZipCode;
                City = original.City;
                Country = original.Country;
             
             
            }

            public FamousAddressIM()
            {
            }



            //InputModel => Model
            public IAddress UpdateModel(IAddress model)
            {
                model.AddressId = AddressId;
                model.StreetAddress = StreetAddress;
                model.ZipCode = ZipCode;
                model.City = City;
                model.Country = Country;
       
            
                return model;
            }
            #endregion

        }
        #endregion

        #region Server Side Validation
        private bool IsValid(string[] validateOnlyKeys = null)
        {
            InvalidKeys = ModelState
               .Where(s => s.Value.ValidationState == ModelValidationState.Invalid);

            if (validateOnlyKeys != null)
            {
                InvalidKeys = InvalidKeys.Where(s => validateOnlyKeys.Any(vk => vk == s.Key));
            }

            ValidationErrorMsgs = InvalidKeys.SelectMany(e => e.Value.Errors).Select(e => e.ErrorMessage);
            HasValidationErrors = InvalidKeys.Any();

            return !HasValidationErrors;
        }
        #endregion
    }
}

GoodFriends_ProjectB_RazorPages/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace GoodFriends_ProjectB_RazorPages.Pages;

public class PrivacyModel : PageModel
{
    private readonly ILogger<PrivacyModel> _logger;

    public PrivacyModel(ILogger<PrivacyModel> logger)
    {
        _logger = logger;
    }

    public void OnGet()
    {
    }
}

GoodFriends_ProjectB_RazorPages/Pages/FriendCountryList.cshtml
@page
@model FriendCountryList
@{
    ViewData["Title"] = "FriendCountryList";
}

<!-- Page list-of-quotes -->
<div class="container px-4 py-4" id="list-of-quotes">
    <h2 class="pb-2 border-bottom">Overview Friends by country</h2>

    <p>Overview Friends by country</p>

   @foreach( var item in Model.Friends)
        {
        <!-- Page friends-by-country -->
    <div class="container px-4 py-4" id="friends-by-country">
        <h2 class="pb-2 border-bottom">Friends by country</h2>
        <p>Here is a list of what cities my friends are living in.</p>
    
     
        <div class="row row-cols-3 row-cols-lg-12 align-items-stretch g-4 py-5">
          <a href="#friends-in-a-country" class="text-decoration-none">
            <div class="col">
              <div class="card card-cover h-100 overflow-hidden text-bg-dark rounded-4 shadow-lg" style="background-image: url('./img/unsplash-photo-3.jpg');">
                <div class="d-flex flex-column h-100 p-5 pb-3 text-white text-shadow-1">
                  <h3 class="pt-1 mt-1 mb-4 display-6 lh-1 fw-bold">@item.Address</h3>
                    <p class="fs-5">@item.FirstName @item.LastName </p>
                </div>
              </div>
            </div>
          </a>

        </div>
        
    </div>
    }

    


    
      

GoodFriends_ProjectB_RazorPages/Pages/FriendList.cshtml
@page
@model FriendList
@{
    ViewData["Title"] = "FriendList";
}

<!-- Page list-of-quotes -->
<div class="container px-4 py-4" id="list-of-quotes">
    <h2 class="pb-2 border-bottom">A List of Friends and their quotes and Birthdate</h2>

 
    <p>Below are some Friends and their quotes</p>

    <form method="post">

    <input type="hidden" name="id" data-seido-selected-item-id-target />

    @foreach (var item in Model.Friends)
    {
        <div class="row mb-2 text-center">
            <label for="named" class="form-label">Names</label>

            <div class="col-md-10 themed-grid-col">

                @item.FirstName @item.LastName
        <br>
                 @foreach( var quote in item.Quotes )
               {
                 <label for="quotes" class="form-label">Quote</label>
                 <div class="col-md-16  text-end">@quote.QuoteText 

                          <button type="button" class="btn btn-success btn-sm m-1"
                                data-seido-selected-item-id="@quote?.QuoteId"
                                data-bs-toggle="modal" data-bs-target="#dangerDelQModal"
                                @quote?.QuoteId
                                data-seido-modal-title="Delete @quote?.QuoteId?" 
                                data-seido-modal-body=" @quote?.QuoteText"
                                data-seido-modal-cancel="No"
                                data-seido-modal-Ok="Delete" 
                                >Del</button>
                 </div>
               }
        <br>

                    @foreach( var pet in item.Pets )
               {
                <label for="pet" class="form-label">Pet</label>
                 <div class="col-md-16  text-end">@pet.Name the @pet.Mood @pet.Kind 

                    
                          <button type="button" class="btn btn-success btn-sm m-1"
                                                        data-seido-selected-item-id="@pet?.PetId"
                                                        data-bs-toggle="modal" data-bs-target="#dangerDelPModal"
                                                        @pet?.PetId
                                                        data-seido-modal-title="DeletePet @pet?.PetId?" 
                                                        data-seido-modal-body="@pet?.Name the @pet?.Mood @pet?.Kind "
                                                        data-seido-modal-cancel="No"
                                                        data-seido-modal-Ok="DeletePet" 
                                        >Del</button>
                 </div>
               }


               
            </div>
            <div class="col-md-2 themed-grid-col">
@*                 <a href="~/Studies/Model/ModelView?id=@item.FriendId" class="btn btn-success btn-sm" type="button">View</a> *@
             <a asp-page="/Model/ModelView"w" asp-route-id=@item.FriendId class="btn btn-success btn-sm" type="button">View</a>
                   
            </div>
        </div>
    }


        <div class="modal fade" id="dangerDelQModal" tabindex="-1" aria-labelledby="softModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title text-danger" id="softModalLabel">Confirm deletion</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                      Quote to be Deleted
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                    <button type="submit" asp-page-handler="Delete" class="btn btn-primary btn-danger" data-bs-dismiss="modal">Ok</button>
                </div>
            </div>
        </div>
    </div>


     <div class="modal fade" id="dangerDelPModal" tabindex="-1" aria-labelledby="softModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title text-danger" id="softModalLabel">Confirm deletion</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                      Pet to be Delete
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                    <button type="submit" asp-page-handler="DeletePet" class="btn btn-primary btn-danger" data-bs-dismiss="modal">Ok</button>
                </div>
            </div>
        </div>
    </div>
    </form>
       <nav aria-label="Standard pagination example">
        <ul class="pagination">
            <li class="page-item">
                <a class="page-link" asp-page="FriendList" asp-route-pagenr=@Model.PrevPageNr asp-route-search=@Model.SearchFilter aria-label="Previous">@*&search=@Model.SearchFilter*@
                    <span aria-hidden="true">&laquo;</span>
                </a>
            </li>
            @for (int i = 0; i < Model.NrVisiblePages; i++)
            {
                <li class="page-item">
                    <a class="page-link" asp-page="FriendList" asp-route-pagenr=@i asp-route-search=@Model.SearchFilter>@(i+1)</a>@*&search=@Model.SearchFilter*@
                </li>

            }
            <li class="page-item">
                <a class="page-link" asp-page="FriendList" asp-route-pagenr=@Model.NextPageNr asp-route-search=@Model.SearchFilter aria-label="Next">@*&search=@Model.SearchFilter*@
                    <span aria-hidden="true">&raquo;</span>
                </a>
            </li>
        </ul>
    </nav>

    
      
 

GoodFriends_ProjectB_RazorPages/Pages/InputModelAddress.cshtml
@page
@model  GoodFriends_ProjectB_RazorPages.Pages.Pages.InputModelAddress 
@{
    ViewData["Title"] = " InputModelAddress";
}
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@attribute [IgnoreAntiforgeryToken]
<!-- Page view-quote -->
<div class="container px-4 py-4" id="view-group">
    <form class="needs-validation" method="post" novalidate>
        
       <!-- <input type="hidden" name="FriendId" data-seido-selected-item-id-target /> -->
      
        <!-- Hidden fields used to bind input model -->
        <input asp-for="AddressIM.AddressId" value="@Model.AddressIM?.AddressId" type="hidden" />
        <input asp-for="AddressIM.StatusIM" value="@Model.AddressIM?.StatusIM" type="hidden" />
     


        <h2 class="pb-2 border-bottom">
            @Model.PageHeader
            <button class="btn btn-primary-outline" type="submit" asp-page-handler="Save">
                <svg class="bi text-body-secondary flex-shrink-0 me-3" width="1.75em" height="1.75em"><use xlink:href="#save" /></svg>
            </button>
            @if (Model.AddressIM?.StatusIM != GoodFriends_ProjectB_RazorPages.Pages.Pages.InputModelAddress.StatusIM.Inserted)
            {
                <button class="btn btn-primary-outline" type="submit" asp-page-handler="Undo">
                    <svg class="bi text-body-secondary flex-shrink-0 me-3" width="1.75em" height="1.75em"><use xlink:href="#undo" /></svg>
                </button>
            }
        </h2>

        @if (Model.ErrorMessage != null)
        {
            <div class="row mb-1 text-center">
                <span class="alert alert-danger" role="alert">
                    @Model.ErrorMessage
                </span>
            </div>
        }
        else
        {
            <!-- Server side validation errors, rough but just in case client side validation is not working or tampered with -->
            @if (Model.HasValidationErrors)
            {
                <div class="row g-3">
                    @foreach (var item in Model.ValidationErrorMsgs)
                    {
                        <span class="alert alert-danger" role="alert">
                            @item
                        </span>
                    }
                </div>
            }
            <div class="row row-cols-1 row-cols-lg-4 align-items-stretch g-4 py-5">
                <div class="col-md-7 col-lg-10">
                    <div class="row g-3">
                       
                        
                            <div class="col-sm-12">
                                <label for="streetAddress" class="form-label">Adress</label>
                                <input type="text" class="form-control" asp-for="AddressIM.StreetAddress" id="address" value="@Model.AddressIM?.StreetAddress">
                                <span asp-validation-for="AddressIM.StreetAddress" class="invalid-feedback"></span>                                
                                
                            </div>

                            <div class="col-sm-12">
                                <label for="zipCode" class="form-label">ZipCode</label>
                                <input type="text" class="form-control" asp-for="AddressIM.ZipCode" id="zipCode" value="@Model.AddressIM?.ZipCode">
                                <span asp-validation-for="AddressIM.ZipCode" class="invalid-feedback"></span>
                                </div>

                            <div class="col-sm-12">
                                <label for="city" class="form-label">City</label>
                                <input type="text" class="form-control" asp-for="AddressIM.City" id="address" value="@Model.AddressIM?.City">
                                <span asp-validation-for="AddressIM.City" class="invalid-feedback"></span>
                                </div>
                            <div class="col-sm-12">
                                <label for="country" class="form-label">Country</label>
                                <input type="text" class="form-control" asp-for="AddressIM.Country" id="address" value="@Model.AddressIM?.Country">
                                <span asp-validation-for="AddressIM.Country" class="invalid-feedback"></span>
                                </div>
                        

                     
                      
                        <div class="col-sm-6">
                        </div>
                      
                    </div>
                </div>
            </div>

        }
    </form>

    <!-- inital template that can be easily hidden -->
    <div class="d-none">
        <form class="needs-validation" method="post" novalidate>
            <h2 class="pb-2 border-bottom">
                TEMPLATE
                <button class="btn btn-primary-outline" type="submit" asp-page-handler="Save">
                    <svg class="bi text-body-secondary flex-shrink-0 me-3" width="1.75em" height="1.75em"><use xlink:href="#save" /></svg>
                </button>
                <button class="btn btn-primary-outline" type="submit" asp-page-handler="Undo">
                    <svg class="bi text-body-secondary flex-shrink-0 me-3" width="1.75em" height="1.75em"><use xlink:href="#undo" /></svg>
                </button>
            </h2>

            <div class="row row-cols-1 row-cols-lg-4 align-items-stretch g-4 py-5">
                <div class="col-md-7 col-lg-10">
                    <div class="row g-3">
                        <div class="col-sm-6">
                            <label for="author" class="form-label">Author</label>
                            <input type="text" class="form-control" id="author" value="Sir Connan Doyle" readonly>
                        </div>
                        <div class="col-sm-6">
                        </div>
                        <div class="col-sm-12">
                            <label for="quote" class="form-label">Quote</label>
                            <input type="text" class="form-control" id="quote" value="Sherlock is best" readonly>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>

 @section script
{
    <!-- -->
    <partial name="_ValidationScriptsPartial" />
}
 